"""Kuiper worlds: the card draws, not just decides.

The same case index that yields a verdict also yields the PICTURE of that
design - module positions and the cable route through them - computed on the
card in one fused kernel. The card emits geometry; the page draws it. Same
index, same world, every time, with nothing stored: eighteen quintillion No
Man's Sky planets fit in a few hundred megabytes for exactly this reason.

This is the UI rule made literal. An operation that cannot be seen is not an
operation, so the geometry is generated by the same pass that generates the
answer, rather than being drawn afterwards by hand.

    python worlds.py                 generate, verify, write worlds.svg

Verified before anything is drawn: the card's geometry must equal the
processor's, point for point.
"""
import io
import os
import sys
import time

import numpy as np

try:
    import cupy as cp
except Exception as exc:                                  # pragma: no cover
    print("cupy unavailable: %r" % (exc,))
    sys.exit(1)

# ---- the design space. Module is class T660: 1303 mm wide in portrait.
W_MM, GAP_MM = 1303.0, 20.0
PITCH = (W_MM + GAP_MM) / 1000.0          # metres between module centres
SERIES = list(range(20, 35))              # 15
ROUTINGS = ["sequential", "leapfrog"]     # 2
ROWS = [1, 2]                             # modules high: 3 axes is a world
NS, NR, NH = len(SERIES), len(ROUTINGS), len(ROWS)
SIZE = NS * NR * NH
MAXPTS = 40                               # 34 modules + entry + return + slack
ROW_M = 2.384 + 0.03                      # module height in portrait, plus gap

_SRC = """
long long r = idx;
int si = (int)(r %% %(NS)d); r /= %(NS)d;
int ri = (int)(r %% %(NR)d); r /= %(NR)d;
int hi = (int)(r %% %(NH)d);

int n    = %(S0)d + si;              // modules in series
int leap = (ri == 1);
int rows = 1 + hi;                   // modules high

double p  = %(PITCH).6f;
double ry = %(ROWM).6f;
int base = (int)(idx * %(MAXPTS)d * 2);
int k = 0;

// the string cable, module centre to module centre
for (int step = 0; step < n; ++step) {
    int m;
    if (!leap) {
        m = step;                                   // straight along the row
    } else if (step < (n + 1) / 2) {
        m = step * 2;                               // out along every other
    } else {
        m = (n - 1 - (step - (n + 1) / 2) * 2);     // back through the skipped
        if (n %% 2 == 0) m = n - 2 - (step - n / 2) * 2;
    }
    double x = (m + 0.5) * p;
    double y = (rows == 2 && (m %% 2)) ? ry : 0.0;
    out[base + k * 2]     = (float)x;
    out[base + k * 2 + 1] = (float)y;
    k++;
}
// the home run: both ends brought back to the inverter side at x = 0
out[base + k * 2]     = (float)((n - 0.5) * p);
out[base + k * 2 + 1] = (float)(-0.9);
k++;
out[base + k * 2]     = 0.0f;
out[base + k * 2 + 1] = (float)(-0.9);
k++;

npts[idx] = k;
""" % {"NS": NS, "NR": NR, "NH": NH, "S0": SERIES[0], "PITCH": PITCH,
       "ROWM": ROW_M, "MAXPTS": MAXPTS}

DRAW = cp.ElementwiseKernel(
    "int64 idx", "raw float32 out, raw int32 npts", _SRC, "ventus_world_draw")


def reference(idx):
    """The same geometry on the processor. This is what the card must equal."""
    out = np.zeros((len(idx), MAXPTS, 2), dtype=np.float32)
    npts = np.zeros(len(idx), dtype=np.int32)
    for j, i in enumerate(idx):
        r = int(i)
        si = r % NS; r //= NS
        ri = r % NR; r //= NR
        hi = r % NH
        n = SERIES[0] + si
        leap = (ri == 1)
        rows = 1 + hi
        k = 0
        for step in range(n):
            if not leap:
                m = step
            elif step < (n + 1) // 2:
                m = step * 2
            else:
                m = n - 1 - (step - (n + 1) // 2) * 2
                if n % 2 == 0:
                    m = n - 2 - (step - n // 2) * 2
            out[j, k] = ((m + 0.5) * PITCH,
                         ROW_M if (rows == 2 and m % 2) else 0.0)
            k += 1
        out[j, k] = ((n - 0.5) * PITCH, -0.9); k += 1
        out[j, k] = (0.0, -0.9); k += 1
        npts[j] = k
    return out, npts


def svg(cases, geo, npts, path):
    """The view, written from the card's own geometry. No hand-drawing."""
    cols, cell_w, cell_h, pad = 3, 360.0, 150.0, 14.0
    rows_n = (len(cases) + cols - 1) // cols
    W = cols * cell_w + pad * 2
    H = rows_n * cell_h + pad * 2 + 46
    s = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %.0f %.0f" '
         'width="100%%" style="background:#07090d;font-family:ui-monospace,'
         'Menlo,Consolas,monospace">' % (W, H)]
    s.append('<text x="%.0f" y="26" fill="#fff" font-size="15">Kuiper worlds '
             '&#8212; %d designs, geometry generated on the card</text>'
             % (pad, len(cases)))
    s.append('<text x="%.0f" y="42" fill="#4ade80" font-size="10.5">every '
             'point below came from the same index that yields the verdict; '
             'nothing here was drawn by hand</text>' % pad)
    for c, case in enumerate(cases):
        gx = pad + (c % cols) * cell_w
        gy = pad + 46 + (c // cols) * cell_h
        r = case
        si = r % NS; r //= NS
        ri = r % NR; r //= NR
        hi = r % NH
        n, routing, rows = SERIES[0] + si, ROUTINGS[ri], 1 + ROWS.index(ROWS[hi]) + 0
        rows = ROWS[hi]
        pts = geo[c][:npts[c]]
        xs, ys = pts[:, 0], pts[:, 1]
        x0, x1 = float(xs.min()), float(xs.max())
        y0, y1 = float(ys.min()), float(ys.max())
        sx = (cell_w - 34) / max(x1 - x0, 1e-6)
        sy = (cell_h - 58) / max(y1 - y0, 1e-6)
        k = min(sx, sy)

        def P(x, y):
            return (gx + 17 + (x - x0) * k, gy + 34 + (y1 - y) * k)

        # modules first, so the cable is drawn over them
        for m in range(n):
            mx = (m + 0.5) * PITCH
            my = ROW_M if (rows == 2 and m % 2) else 0.0
            px, py = P(mx, my)
            s.append('<rect x="%.1f" y="%.1f" width="%.1f" height="%.1f" '
                     'fill="#11151f" stroke="#1b2030" stroke-width="0.7"/>'
                     % (px - (W_MM / 1000.0) * k / 2, py - 5,
                        max(1.2, (W_MM / 1000.0) * k), 10))
        d = " ".join("%.1f,%.1f" % P(float(x), float(y)) for x, y in pts)
        s.append('<polyline points="%s" fill="none" stroke="#5ec8f2" '
                 'stroke-width="1.5"/>' % d)
        s.append('<text x="%.0f" y="%.0f" fill="#cfe3f2" font-size="10">'
                 '%d in series &#183; %s &#183; %d high</text>'
                 % (gx + 17, gy + 20, n, routing, rows))
        s.append('<text x="%.0f" y="%.0f" fill="#8b93a7" font-size="9">'
                 'index %d &#183; %.2f kW DC at 660 Wp</text>'
                 % (gx + 17, gy + cell_h - 16, case, n * 660.0 / 1000.0))
    s.append("</svg>")
    io.open(path, "w", encoding="utf-8", newline="\n").write("\n".join(s))


def main():
    print("world space: %d designs over 3 axes %s" % (SIZE, [NS, NR, NH]))
    idx = cp.arange(SIZE, dtype=cp.int64)
    out = cp.zeros(SIZE * MAXPTS * 2, dtype=cp.float32)
    npts = cp.zeros(SIZE, dtype=cp.int32)
    cp.cuda.Stream.null.synchronize()
    t0 = time.perf_counter()
    DRAW(idx, out, npts)
    cp.cuda.Stream.null.synchronize()
    sec = time.perf_counter() - t0
    geo = cp.asnumpy(out).reshape(SIZE, MAXPTS, 2)
    npt = cp.asnumpy(npts)

    ref_geo, ref_npt = reference(np.arange(SIZE))
    same_n = bool((npt == ref_npt).all())
    worst = float(np.abs(geo - ref_geo).max())
    print("verified against the processor: point counts equal = %s, worst "
          "coordinate difference = %.3e" % (same_n, worst))
    if not same_n or worst > 0:
        print("FAIL: the card and the processor drew different worlds")
        return 1
    print("the card drew %d complete worlds in %.4f s (%s designs/s)\n"
          % (SIZE, sec, "{:,.0f}".format(SIZE / sec)))

    show = [SERIES.index(n) + NS * (r + NR * h)
            for n in (24, 30, 34) for r in (0, 1) for h in (0, 1)][:12]
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "worlds.svg")
    svg(show, geo[show], npt[show], path)
    print("wrote %s - %d of them drawn, every coordinate from the card"
          % (os.path.basename(path), len(show)))
    print("\nNot claimed: this is the cable ROUTE, not a cable schedule; no")
    print("length, loss or sizing figure is stated and none was computed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
